-- MySQL Script generated by MySQL Workbench
-- Sun Nov 23 22:23:11 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema signal
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema signal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `signal` DEFAULT CHARACTER SET utf8 ;
USE `signal` ;

-- -----------------------------------------------------
-- Table `signal`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `signal`.`User` ;

CREATE TABLE IF NOT EXISTS `signal`.`User` (
  `CPF` VARCHAR(11) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `DateOfBirth` DATE NOT NULL,
  `UserType` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CPF`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `signal`.`Department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `signal`.`Department` ;

CREATE TABLE IF NOT EXISTS `signal`.`Department` (
  `DepartmentCode` VARCHAR(45) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`DepartmentCode`),
  UNIQUE INDEX `DepartmentCode_UNIQUE` (`DepartmentCode` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `signal`.`Team`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `signal`.`Team` ;

CREATE TABLE IF NOT EXISTS `signal`.`Team` (
  `idTeam` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTeam`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `signal`.`Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `signal`.`Employee` ;

CREATE TABLE IF NOT EXISTS `signal`.`Employee` (
  `idEmployee` INT NOT NULL AUTO_INCREMENT,
  `Department_DepartmentCode` VARCHAR(45) NOT NULL,
  `Role` VARCHAR(45) NOT NULL,
  `Team_idTeam` INT NOT NULL,
  `User_CPF` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`Department_DepartmentCode`, `Team_idTeam`, `User_CPF`),
  UNIQUE INDEX `idEmployee_UNIQUE` (`idEmployee` ASC) VISIBLE,
  INDEX `fk_Employee_Department1_idx` (`Department_DepartmentCode` ASC) VISIBLE,
  INDEX `fk_Employee_Team1_idx` (`Team_idTeam` ASC) VISIBLE,
  INDEX `fk_Employee_User1_idx` (`User_CPF` ASC) VISIBLE,
  CONSTRAINT `fk_Employee_Department1`
    FOREIGN KEY (`Department_DepartmentCode`)
    REFERENCES `signal`.`Department` (`DepartmentCode`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Employee_Team1`
    FOREIGN KEY (`Team_idTeam`)
    REFERENCES `signal`.`Team` (`idTeam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Employee_User1`
    FOREIGN KEY (`User_CPF`)
    REFERENCES `signal`.`User` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `signal`.`Location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `signal`.`Location` ;

CREATE TABLE IF NOT EXISTS `signal`.`Location` (
  `idLocation` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Latitude` DECIMAL(9,6) NOT NULL,
  `Longitude` DECIMAL(9,6) NOT NULL,
  PRIMARY KEY (`idLocation`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `signal`.`Mission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `signal`.`Mission` ;

CREATE TABLE IF NOT EXISTS `signal`.`Mission` (
  `idMission` INT NOT NULL AUTO_INCREMENT,
  `ExtraInstructions` VARCHAR(100) NULL,
  `User_CPF` VARCHAR(11) NOT NULL,
  `Team_idTeam` INT NOT NULL,
  `Location_idLocation` INT NOT NULL,
  `completed` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`idMission`, `User_CPF`, `Team_idTeam`, `Location_idLocation`),
  INDEX `fk_Mission_User1_idx` (`User_CPF` ASC) VISIBLE,
  INDEX `fk_Mission_Team1_idx` (`Team_idTeam` ASC) VISIBLE,
  INDEX `fk_Mission_Location1_idx` (`Location_idLocation` ASC) VISIBLE,
  CONSTRAINT `fk_Mission_User1`
    FOREIGN KEY (`User_CPF`)
    REFERENCES `signal`.`User` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mission_Team1`
    FOREIGN KEY (`Team_idTeam`)
    REFERENCES `signal`.`Team` (`idTeam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mission_Location1`
    FOREIGN KEY (`Location_idLocation`)
    REFERENCES `signal`.`Location` (`idLocation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `signal`.`Equipment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `signal`.`Equipment` ;

CREATE TABLE IF NOT EXISTS `signal`.`Equipment` (
  `idEquipment` INT NOT NULL AUTO_INCREMENT,
  `Type` VARCHAR(45) NOT NULL,
  `Desctiption` VARCHAR(45) NOT NULL,
  `Last_maintenance` DATE NOT NULL,
  `Team_idTeam` INT NOT NULL,
  PRIMARY KEY (`idEquipment`, `Team_idTeam`),
  INDEX `fk_Equipment_Team1_idx` (`Team_idTeam` ASC) VISIBLE,
  CONSTRAINT `fk_Equipment_Team1`
    FOREIGN KEY (`Team_idTeam`)
    REFERENCES `signal`.`Team` (`idTeam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `signal`.`Clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `signal`.`Clients` ;

CREATE TABLE IF NOT EXISTS `signal`.`Clients` (
  `idClients` INT NOT NULL AUTO_INCREMENT,
  `ContactInfo` VARCHAR(45) NOT NULL,
  `User_CPF` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`idClients`, `User_CPF`),
  UNIQUE INDEX `idClients_UNIQUE` (`idClients` ASC) VISIBLE,
  INDEX `fk_Clients_User_idx` (`User_CPF` ASC) VISIBLE,
  CONSTRAINT `fk_Clients_User`
    FOREIGN KEY (`User_CPF`)
    REFERENCES `signal`.`User` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
